/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as RoomRoomIdRouteImport } from './routes/room/$roomId'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'
import { Route as PrivatepatientRouteRouteImport } from './routes/_private/(patient)/route'
import { Route as PrivateclinicianRouteRouteImport } from './routes/_private/(clinician)/route'
import { Route as PrivateadmSharedRouteRouteImport } from './routes/_private/(adm-shared)/route'
import { Route as PrivateProfileIndexRouteImport } from './routes/_private/profile.index'
import { Route as PrivateProfileEditRouteImport } from './routes/_private/profile.edit'
import { Route as PrivatepatientBookRouteImport } from './routes/_private/(patient)/book'
import { Route as PrivateadmSharedLogsRouteImport } from './routes/_private/(adm-shared)/logs'
import { Route as PublicActivateOtpIndexRouteImport } from './routes/_public/activate/otp.index'
import { Route as PrivatesharedContentIndexRouteImport } from './routes/_private/(shared)/content/index'
import { Route as PrivatesharedAppointmentsIndexRouteImport } from './routes/_private/(shared)/appointments/index'
import { Route as PrivatepatientRecordsIndexRouteImport } from './routes/_private/(patient)/records.index'
import { Route as PrivateclinicianSchedulesIndexRouteImport } from './routes/_private/(clinician)/schedules/index'
import { Route as PrivateclinicianPatientsIndexRouteImport } from './routes/_private/(clinician)/patients/index'
import { Route as PrivateadmSharedUsersIndexRouteImport } from './routes/_private/(adm-shared)/users/index'
import { Route as PublicActivateOtpUpdateRouteImport } from './routes/_public/activate/otp.update'
import { Route as PrivatesharedContentContentIdRouteImport } from './routes/_private/(shared)/content/$contentId'
import { Route as PrivatesharedAppointmentsAppointmentIdRouteImport } from './routes/_private/(shared)/appointments/$appointmentId'
import { Route as PrivatepatientRecordsSoapIdRouteImport } from './routes/_private/(patient)/records.$soapId'
import { Route as PrivateclinicianSchedulesCreateRouteImport } from './routes/_private/(clinician)/schedules/create'
import { Route as PrivateclinicianSchedulesSlotIdRouteImport } from './routes/_private/(clinician)/schedules/$slotId'
import { Route as PrivateadmSharedUsersUserIdRouteImport } from './routes/_private/(adm-shared)/users/$userId'
import { Route as PrivatesharedContentAdmRouteRouteImport } from './routes/_private/(shared)/content/_adm/route'
import { Route as PrivateclinicianPatientsPatientIdIndexRouteImport } from './routes/_private/(clinician)/patients/$patientId.index'
import { Route as PrivatesharedContentAdmCreateRouteImport } from './routes/_private/(shared)/content/_adm/create'
import { Route as PrivateclinicianPatientsPatientIdCreateRouteImport } from './routes/_private/(clinician)/patients/$patientId.create'
import { Route as PrivatesharedContentAdmContentIdEditRouteImport } from './routes/_private/(shared)/content/_adm/$contentId.edit'
import { Route as PrivateclinicianPatientsPatientIdSoapSoapIdIndexRouteImport } from './routes/_private/(clinician)/patients/$patientId.soap.$soapId.index'
import { Route as PrivateclinicianPatientsPatientIdSoapSoapIdUpdateRouteImport } from './routes/_private/(clinician)/patients/$patientId.soap.$soapId.update'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivatepatientRouteRoute = PrivatepatientRouteRouteImport.update({
  id: '/(patient)',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateclinicianRouteRoute = PrivateclinicianRouteRouteImport.update({
  id: '/(clinician)',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateadmSharedRouteRoute = PrivateadmSharedRouteRouteImport.update({
  id: '/(adm-shared)',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateProfileIndexRoute = PrivateProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateProfileEditRoute = PrivateProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivatepatientBookRoute = PrivatepatientBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PrivatepatientRouteRoute,
} as any)
const PrivateadmSharedLogsRoute = PrivateadmSharedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => PrivateadmSharedRouteRoute,
} as any)
const PublicActivateOtpIndexRoute = PublicActivateOtpIndexRouteImport.update({
  id: '/activate/otp/',
  path: '/activate/otp/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivatesharedContentIndexRoute =
  PrivatesharedContentIndexRouteImport.update({
    id: '/(shared)/content/',
    path: '/content/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivatesharedAppointmentsIndexRoute =
  PrivatesharedAppointmentsIndexRouteImport.update({
    id: '/(shared)/appointments/',
    path: '/appointments/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivatepatientRecordsIndexRoute =
  PrivatepatientRecordsIndexRouteImport.update({
    id: '/records/',
    path: '/records/',
    getParentRoute: () => PrivatepatientRouteRoute,
  } as any)
const PrivateclinicianSchedulesIndexRoute =
  PrivateclinicianSchedulesIndexRouteImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => PrivateclinicianRouteRoute,
  } as any)
const PrivateclinicianPatientsIndexRoute =
  PrivateclinicianPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => PrivateclinicianRouteRoute,
  } as any)
const PrivateadmSharedUsersIndexRoute =
  PrivateadmSharedUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => PrivateadmSharedRouteRoute,
  } as any)
const PublicActivateOtpUpdateRoute = PublicActivateOtpUpdateRouteImport.update({
  id: '/activate/otp/update',
  path: '/activate/otp/update',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivatesharedContentContentIdRoute =
  PrivatesharedContentContentIdRouteImport.update({
    id: '/(shared)/content/$contentId',
    path: '/content/$contentId',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivatesharedAppointmentsAppointmentIdRoute =
  PrivatesharedAppointmentsAppointmentIdRouteImport.update({
    id: '/(shared)/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivatepatientRecordsSoapIdRoute =
  PrivatepatientRecordsSoapIdRouteImport.update({
    id: '/records/$soapId',
    path: '/records/$soapId',
    getParentRoute: () => PrivatepatientRouteRoute,
  } as any)
const PrivateclinicianSchedulesCreateRoute =
  PrivateclinicianSchedulesCreateRouteImport.update({
    id: '/schedules/create',
    path: '/schedules/create',
    getParentRoute: () => PrivateclinicianRouteRoute,
  } as any)
const PrivateclinicianSchedulesSlotIdRoute =
  PrivateclinicianSchedulesSlotIdRouteImport.update({
    id: '/schedules/$slotId',
    path: '/schedules/$slotId',
    getParentRoute: () => PrivateclinicianRouteRoute,
  } as any)
const PrivateadmSharedUsersUserIdRoute =
  PrivateadmSharedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => PrivateadmSharedRouteRoute,
  } as any)
const PrivatesharedContentAdmRouteRoute =
  PrivatesharedContentAdmRouteRouteImport.update({
    id: '/(shared)/content/_adm',
    path: '/content',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateclinicianPatientsPatientIdIndexRoute =
  PrivateclinicianPatientsPatientIdIndexRouteImport.update({
    id: '/patients/$patientId/',
    path: '/patients/$patientId/',
    getParentRoute: () => PrivateclinicianRouteRoute,
  } as any)
const PrivatesharedContentAdmCreateRoute =
  PrivatesharedContentAdmCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => PrivatesharedContentAdmRouteRoute,
  } as any)
const PrivateclinicianPatientsPatientIdCreateRoute =
  PrivateclinicianPatientsPatientIdCreateRouteImport.update({
    id: '/patients/$patientId/create',
    path: '/patients/$patientId/create',
    getParentRoute: () => PrivateclinicianRouteRoute,
  } as any)
const PrivatesharedContentAdmContentIdEditRoute =
  PrivatesharedContentAdmContentIdEditRouteImport.update({
    id: '/$contentId/edit',
    path: '/$contentId/edit',
    getParentRoute: () => PrivatesharedContentAdmRouteRoute,
  } as any)
const PrivateclinicianPatientsPatientIdSoapSoapIdIndexRoute =
  PrivateclinicianPatientsPatientIdSoapSoapIdIndexRouteImport.update({
    id: '/patients/$patientId/soap/$soapId/',
    path: '/patients/$patientId/soap/$soapId/',
    getParentRoute: () => PrivateclinicianRouteRoute,
  } as any)
const PrivateclinicianPatientsPatientIdSoapSoapIdUpdateRoute =
  PrivateclinicianPatientsPatientIdSoapSoapIdUpdateRouteImport.update({
    id: '/patients/$patientId/soap/$soapId/update',
    path: '/patients/$patientId/soap/$soapId/update',
    getParentRoute: () => PrivateclinicianRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/logs': typeof PrivateadmSharedLogsRoute
  '/book': typeof PrivatepatientBookRoute
  '/profile/edit': typeof PrivateProfileEditRoute
  '/profile/': typeof PrivateProfileIndexRoute
  '/content': typeof PrivatesharedContentAdmRouteRouteWithChildren
  '/users/$userId': typeof PrivateadmSharedUsersUserIdRoute
  '/schedules/$slotId': typeof PrivateclinicianSchedulesSlotIdRoute
  '/schedules/create': typeof PrivateclinicianSchedulesCreateRoute
  '/records/$soapId': typeof PrivatepatientRecordsSoapIdRoute
  '/appointments/$appointmentId': typeof PrivatesharedAppointmentsAppointmentIdRoute
  '/content/$contentId': typeof PrivatesharedContentContentIdRoute
  '/activate/otp/update': typeof PublicActivateOtpUpdateRoute
  '/users/': typeof PrivateadmSharedUsersIndexRoute
  '/patients/': typeof PrivateclinicianPatientsIndexRoute
  '/schedules/': typeof PrivateclinicianSchedulesIndexRoute
  '/records/': typeof PrivatepatientRecordsIndexRoute
  '/appointments/': typeof PrivatesharedAppointmentsIndexRoute
  '/content/': typeof PrivatesharedContentIndexRoute
  '/activate/otp/': typeof PublicActivateOtpIndexRoute
  '/patients/$patientId/create': typeof PrivateclinicianPatientsPatientIdCreateRoute
  '/content/create': typeof PrivatesharedContentAdmCreateRoute
  '/patients/$patientId/': typeof PrivateclinicianPatientsPatientIdIndexRoute
  '/content/$contentId/edit': typeof PrivatesharedContentAdmContentIdEditRoute
  '/patients/$patientId/soap/$soapId/update': typeof PrivateclinicianPatientsPatientIdSoapSoapIdUpdateRoute
  '/patients/$patientId/soap/$soapId/': typeof PrivateclinicianPatientsPatientIdSoapSoapIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/logs': typeof PrivateadmSharedLogsRoute
  '/book': typeof PrivatepatientBookRoute
  '/profile/edit': typeof PrivateProfileEditRoute
  '/profile': typeof PrivateProfileIndexRoute
  '/content': typeof PrivatesharedContentIndexRoute
  '/users/$userId': typeof PrivateadmSharedUsersUserIdRoute
  '/schedules/$slotId': typeof PrivateclinicianSchedulesSlotIdRoute
  '/schedules/create': typeof PrivateclinicianSchedulesCreateRoute
  '/records/$soapId': typeof PrivatepatientRecordsSoapIdRoute
  '/appointments/$appointmentId': typeof PrivatesharedAppointmentsAppointmentIdRoute
  '/content/$contentId': typeof PrivatesharedContentContentIdRoute
  '/activate/otp/update': typeof PublicActivateOtpUpdateRoute
  '/users': typeof PrivateadmSharedUsersIndexRoute
  '/patients': typeof PrivateclinicianPatientsIndexRoute
  '/schedules': typeof PrivateclinicianSchedulesIndexRoute
  '/records': typeof PrivatepatientRecordsIndexRoute
  '/appointments': typeof PrivatesharedAppointmentsIndexRoute
  '/activate/otp': typeof PublicActivateOtpIndexRoute
  '/patients/$patientId/create': typeof PrivateclinicianPatientsPatientIdCreateRoute
  '/content/create': typeof PrivatesharedContentAdmCreateRoute
  '/patients/$patientId': typeof PrivateclinicianPatientsPatientIdIndexRoute
  '/content/$contentId/edit': typeof PrivatesharedContentAdmContentIdEditRoute
  '/patients/$patientId/soap/$soapId/update': typeof PrivateclinicianPatientsPatientIdSoapSoapIdUpdateRoute
  '/patients/$patientId/soap/$soapId': typeof PrivateclinicianPatientsPatientIdSoapSoapIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_private/(adm-shared)': typeof PrivateadmSharedRouteRouteWithChildren
  '/_private/(clinician)': typeof PrivateclinicianRouteRouteWithChildren
  '/_private/(patient)': typeof PrivatepatientRouteRouteWithChildren
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/(adm-shared)/logs': typeof PrivateadmSharedLogsRoute
  '/_private/(patient)/book': typeof PrivatepatientBookRoute
  '/_private/profile/edit': typeof PrivateProfileEditRoute
  '/_private/profile/': typeof PrivateProfileIndexRoute
  '/_private/(shared)/content/_adm': typeof PrivatesharedContentAdmRouteRouteWithChildren
  '/_private/(adm-shared)/users/$userId': typeof PrivateadmSharedUsersUserIdRoute
  '/_private/(clinician)/schedules/$slotId': typeof PrivateclinicianSchedulesSlotIdRoute
  '/_private/(clinician)/schedules/create': typeof PrivateclinicianSchedulesCreateRoute
  '/_private/(patient)/records/$soapId': typeof PrivatepatientRecordsSoapIdRoute
  '/_private/(shared)/appointments/$appointmentId': typeof PrivatesharedAppointmentsAppointmentIdRoute
  '/_private/(shared)/content/$contentId': typeof PrivatesharedContentContentIdRoute
  '/_public/activate/otp/update': typeof PublicActivateOtpUpdateRoute
  '/_private/(adm-shared)/users/': typeof PrivateadmSharedUsersIndexRoute
  '/_private/(clinician)/patients/': typeof PrivateclinicianPatientsIndexRoute
  '/_private/(clinician)/schedules/': typeof PrivateclinicianSchedulesIndexRoute
  '/_private/(patient)/records/': typeof PrivatepatientRecordsIndexRoute
  '/_private/(shared)/appointments/': typeof PrivatesharedAppointmentsIndexRoute
  '/_private/(shared)/content/': typeof PrivatesharedContentIndexRoute
  '/_public/activate/otp/': typeof PublicActivateOtpIndexRoute
  '/_private/(clinician)/patients/$patientId/create': typeof PrivateclinicianPatientsPatientIdCreateRoute
  '/_private/(shared)/content/_adm/create': typeof PrivatesharedContentAdmCreateRoute
  '/_private/(clinician)/patients/$patientId/': typeof PrivateclinicianPatientsPatientIdIndexRoute
  '/_private/(shared)/content/_adm/$contentId/edit': typeof PrivatesharedContentAdmContentIdEditRoute
  '/_private/(clinician)/patients/$patientId/soap/$soapId/update': typeof PrivateclinicianPatientsPatientIdSoapSoapIdUpdateRoute
  '/_private/(clinician)/patients/$patientId/soap/$soapId/': typeof PrivateclinicianPatientsPatientIdSoapSoapIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/unauthorized'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/room/$roomId'
    | '/logs'
    | '/book'
    | '/profile/edit'
    | '/profile/'
    | '/content'
    | '/users/$userId'
    | '/schedules/$slotId'
    | '/schedules/create'
    | '/records/$soapId'
    | '/appointments/$appointmentId'
    | '/content/$contentId'
    | '/activate/otp/update'
    | '/users/'
    | '/patients/'
    | '/schedules/'
    | '/records/'
    | '/appointments/'
    | '/content/'
    | '/activate/otp/'
    | '/patients/$patientId/create'
    | '/content/create'
    | '/patients/$patientId/'
    | '/content/$contentId/edit'
    | '/patients/$patientId/soap/$soapId/update'
    | '/patients/$patientId/soap/$soapId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/unauthorized'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/room/$roomId'
    | '/logs'
    | '/book'
    | '/profile/edit'
    | '/profile'
    | '/content'
    | '/users/$userId'
    | '/schedules/$slotId'
    | '/schedules/create'
    | '/records/$soapId'
    | '/appointments/$appointmentId'
    | '/content/$contentId'
    | '/activate/otp/update'
    | '/users'
    | '/patients'
    | '/schedules'
    | '/records'
    | '/appointments'
    | '/activate/otp'
    | '/patients/$patientId/create'
    | '/content/create'
    | '/patients/$patientId'
    | '/content/$contentId/edit'
    | '/patients/$patientId/soap/$soapId/update'
    | '/patients/$patientId/soap/$soapId'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/forbidden'
    | '/unauthorized'
    | '/_private/(adm-shared)'
    | '/_private/(clinician)'
    | '/_private/(patient)'
    | '/_private/dashboard'
    | '/_public/login'
    | '/_public/register'
    | '/room/$roomId'
    | '/_public/'
    | '/_private/(adm-shared)/logs'
    | '/_private/(patient)/book'
    | '/_private/profile/edit'
    | '/_private/profile/'
    | '/_private/(shared)/content/_adm'
    | '/_private/(adm-shared)/users/$userId'
    | '/_private/(clinician)/schedules/$slotId'
    | '/_private/(clinician)/schedules/create'
    | '/_private/(patient)/records/$soapId'
    | '/_private/(shared)/appointments/$appointmentId'
    | '/_private/(shared)/content/$contentId'
    | '/_public/activate/otp/update'
    | '/_private/(adm-shared)/users/'
    | '/_private/(clinician)/patients/'
    | '/_private/(clinician)/schedules/'
    | '/_private/(patient)/records/'
    | '/_private/(shared)/appointments/'
    | '/_private/(shared)/content/'
    | '/_public/activate/otp/'
    | '/_private/(clinician)/patients/$patientId/create'
    | '/_private/(shared)/content/_adm/create'
    | '/_private/(clinician)/patients/$patientId/'
    | '/_private/(shared)/content/_adm/$contentId/edit'
    | '/_private/(clinician)/patients/$patientId/soap/$soapId/update'
    | '/_private/(clinician)/patients/$patientId/soap/$soapId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(patient)': {
      id: '/_private/(patient)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivatepatientRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(clinician)': {
      id: '/_private/(clinician)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateclinicianRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(adm-shared)': {
      id: '/_private/(adm-shared)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateadmSharedRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/profile/': {
      id: '/_private/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof PrivateProfileIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/profile/edit': {
      id: '/_private/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof PrivateProfileEditRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(patient)/book': {
      id: '/_private/(patient)/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof PrivatepatientBookRouteImport
      parentRoute: typeof PrivatepatientRouteRoute
    }
    '/_private/(adm-shared)/logs': {
      id: '/_private/(adm-shared)/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof PrivateadmSharedLogsRouteImport
      parentRoute: typeof PrivateadmSharedRouteRoute
    }
    '/_public/activate/otp/': {
      id: '/_public/activate/otp/'
      path: '/activate/otp'
      fullPath: '/activate/otp/'
      preLoaderRoute: typeof PublicActivateOtpIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/(shared)/content/': {
      id: '/_private/(shared)/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof PrivatesharedContentIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(shared)/appointments/': {
      id: '/_private/(shared)/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof PrivatesharedAppointmentsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(patient)/records/': {
      id: '/_private/(patient)/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof PrivatepatientRecordsIndexRouteImport
      parentRoute: typeof PrivatepatientRouteRoute
    }
    '/_private/(clinician)/schedules/': {
      id: '/_private/(clinician)/schedules/'
      path: '/schedules'
      fullPath: '/schedules/'
      preLoaderRoute: typeof PrivateclinicianSchedulesIndexRouteImport
      parentRoute: typeof PrivateclinicianRouteRoute
    }
    '/_private/(clinician)/patients/': {
      id: '/_private/(clinician)/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PrivateclinicianPatientsIndexRouteImport
      parentRoute: typeof PrivateclinicianRouteRoute
    }
    '/_private/(adm-shared)/users/': {
      id: '/_private/(adm-shared)/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof PrivateadmSharedUsersIndexRouteImport
      parentRoute: typeof PrivateadmSharedRouteRoute
    }
    '/_public/activate/otp/update': {
      id: '/_public/activate/otp/update'
      path: '/activate/otp/update'
      fullPath: '/activate/otp/update'
      preLoaderRoute: typeof PublicActivateOtpUpdateRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/(shared)/content/$contentId': {
      id: '/_private/(shared)/content/$contentId'
      path: '/content/$contentId'
      fullPath: '/content/$contentId'
      preLoaderRoute: typeof PrivatesharedContentContentIdRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(shared)/appointments/$appointmentId': {
      id: '/_private/(shared)/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof PrivatesharedAppointmentsAppointmentIdRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(patient)/records/$soapId': {
      id: '/_private/(patient)/records/$soapId'
      path: '/records/$soapId'
      fullPath: '/records/$soapId'
      preLoaderRoute: typeof PrivatepatientRecordsSoapIdRouteImport
      parentRoute: typeof PrivatepatientRouteRoute
    }
    '/_private/(clinician)/schedules/create': {
      id: '/_private/(clinician)/schedules/create'
      path: '/schedules/create'
      fullPath: '/schedules/create'
      preLoaderRoute: typeof PrivateclinicianSchedulesCreateRouteImport
      parentRoute: typeof PrivateclinicianRouteRoute
    }
    '/_private/(clinician)/schedules/$slotId': {
      id: '/_private/(clinician)/schedules/$slotId'
      path: '/schedules/$slotId'
      fullPath: '/schedules/$slotId'
      preLoaderRoute: typeof PrivateclinicianSchedulesSlotIdRouteImport
      parentRoute: typeof PrivateclinicianRouteRoute
    }
    '/_private/(adm-shared)/users/$userId': {
      id: '/_private/(adm-shared)/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof PrivateadmSharedUsersUserIdRouteImport
      parentRoute: typeof PrivateadmSharedRouteRoute
    }
    '/_private/(shared)/content/_adm': {
      id: '/_private/(shared)/content/_adm'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof PrivatesharedContentAdmRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(clinician)/patients/$patientId/': {
      id: '/_private/(clinician)/patients/$patientId/'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof PrivateclinicianPatientsPatientIdIndexRouteImport
      parentRoute: typeof PrivateclinicianRouteRoute
    }
    '/_private/(shared)/content/_adm/create': {
      id: '/_private/(shared)/content/_adm/create'
      path: '/create'
      fullPath: '/content/create'
      preLoaderRoute: typeof PrivatesharedContentAdmCreateRouteImport
      parentRoute: typeof PrivatesharedContentAdmRouteRoute
    }
    '/_private/(clinician)/patients/$patientId/create': {
      id: '/_private/(clinician)/patients/$patientId/create'
      path: '/patients/$patientId/create'
      fullPath: '/patients/$patientId/create'
      preLoaderRoute: typeof PrivateclinicianPatientsPatientIdCreateRouteImport
      parentRoute: typeof PrivateclinicianRouteRoute
    }
    '/_private/(shared)/content/_adm/$contentId/edit': {
      id: '/_private/(shared)/content/_adm/$contentId/edit'
      path: '/$contentId/edit'
      fullPath: '/content/$contentId/edit'
      preLoaderRoute: typeof PrivatesharedContentAdmContentIdEditRouteImport
      parentRoute: typeof PrivatesharedContentAdmRouteRoute
    }
    '/_private/(clinician)/patients/$patientId/soap/$soapId/': {
      id: '/_private/(clinician)/patients/$patientId/soap/$soapId/'
      path: '/patients/$patientId/soap/$soapId'
      fullPath: '/patients/$patientId/soap/$soapId/'
      preLoaderRoute: typeof PrivateclinicianPatientsPatientIdSoapSoapIdIndexRouteImport
      parentRoute: typeof PrivateclinicianRouteRoute
    }
    '/_private/(clinician)/patients/$patientId/soap/$soapId/update': {
      id: '/_private/(clinician)/patients/$patientId/soap/$soapId/update'
      path: '/patients/$patientId/soap/$soapId/update'
      fullPath: '/patients/$patientId/soap/$soapId/update'
      preLoaderRoute: typeof PrivateclinicianPatientsPatientIdSoapSoapIdUpdateRouteImport
      parentRoute: typeof PrivateclinicianRouteRoute
    }
  }
}

interface PrivateadmSharedRouteRouteChildren {
  PrivateadmSharedLogsRoute: typeof PrivateadmSharedLogsRoute
  PrivateadmSharedUsersUserIdRoute: typeof PrivateadmSharedUsersUserIdRoute
  PrivateadmSharedUsersIndexRoute: typeof PrivateadmSharedUsersIndexRoute
}

const PrivateadmSharedRouteRouteChildren: PrivateadmSharedRouteRouteChildren = {
  PrivateadmSharedLogsRoute: PrivateadmSharedLogsRoute,
  PrivateadmSharedUsersUserIdRoute: PrivateadmSharedUsersUserIdRoute,
  PrivateadmSharedUsersIndexRoute: PrivateadmSharedUsersIndexRoute,
}

const PrivateadmSharedRouteRouteWithChildren =
  PrivateadmSharedRouteRoute._addFileChildren(
    PrivateadmSharedRouteRouteChildren,
  )

interface PrivateclinicianRouteRouteChildren {
  PrivateclinicianSchedulesSlotIdRoute: typeof PrivateclinicianSchedulesSlotIdRoute
  PrivateclinicianSchedulesCreateRoute: typeof PrivateclinicianSchedulesCreateRoute
  PrivateclinicianPatientsIndexRoute: typeof PrivateclinicianPatientsIndexRoute
  PrivateclinicianSchedulesIndexRoute: typeof PrivateclinicianSchedulesIndexRoute
  PrivateclinicianPatientsPatientIdCreateRoute: typeof PrivateclinicianPatientsPatientIdCreateRoute
  PrivateclinicianPatientsPatientIdIndexRoute: typeof PrivateclinicianPatientsPatientIdIndexRoute
  PrivateclinicianPatientsPatientIdSoapSoapIdUpdateRoute: typeof PrivateclinicianPatientsPatientIdSoapSoapIdUpdateRoute
  PrivateclinicianPatientsPatientIdSoapSoapIdIndexRoute: typeof PrivateclinicianPatientsPatientIdSoapSoapIdIndexRoute
}

const PrivateclinicianRouteRouteChildren: PrivateclinicianRouteRouteChildren = {
  PrivateclinicianSchedulesSlotIdRoute: PrivateclinicianSchedulesSlotIdRoute,
  PrivateclinicianSchedulesCreateRoute: PrivateclinicianSchedulesCreateRoute,
  PrivateclinicianPatientsIndexRoute: PrivateclinicianPatientsIndexRoute,
  PrivateclinicianSchedulesIndexRoute: PrivateclinicianSchedulesIndexRoute,
  PrivateclinicianPatientsPatientIdCreateRoute:
    PrivateclinicianPatientsPatientIdCreateRoute,
  PrivateclinicianPatientsPatientIdIndexRoute:
    PrivateclinicianPatientsPatientIdIndexRoute,
  PrivateclinicianPatientsPatientIdSoapSoapIdUpdateRoute:
    PrivateclinicianPatientsPatientIdSoapSoapIdUpdateRoute,
  PrivateclinicianPatientsPatientIdSoapSoapIdIndexRoute:
    PrivateclinicianPatientsPatientIdSoapSoapIdIndexRoute,
}

const PrivateclinicianRouteRouteWithChildren =
  PrivateclinicianRouteRoute._addFileChildren(
    PrivateclinicianRouteRouteChildren,
  )

interface PrivatepatientRouteRouteChildren {
  PrivatepatientBookRoute: typeof PrivatepatientBookRoute
  PrivatepatientRecordsSoapIdRoute: typeof PrivatepatientRecordsSoapIdRoute
  PrivatepatientRecordsIndexRoute: typeof PrivatepatientRecordsIndexRoute
}

const PrivatepatientRouteRouteChildren: PrivatepatientRouteRouteChildren = {
  PrivatepatientBookRoute: PrivatepatientBookRoute,
  PrivatepatientRecordsSoapIdRoute: PrivatepatientRecordsSoapIdRoute,
  PrivatepatientRecordsIndexRoute: PrivatepatientRecordsIndexRoute,
}

const PrivatepatientRouteRouteWithChildren =
  PrivatepatientRouteRoute._addFileChildren(PrivatepatientRouteRouteChildren)

interface PrivatesharedContentAdmRouteRouteChildren {
  PrivatesharedContentAdmCreateRoute: typeof PrivatesharedContentAdmCreateRoute
  PrivatesharedContentAdmContentIdEditRoute: typeof PrivatesharedContentAdmContentIdEditRoute
}

const PrivatesharedContentAdmRouteRouteChildren: PrivatesharedContentAdmRouteRouteChildren =
  {
    PrivatesharedContentAdmCreateRoute: PrivatesharedContentAdmCreateRoute,
    PrivatesharedContentAdmContentIdEditRoute:
      PrivatesharedContentAdmContentIdEditRoute,
  }

const PrivatesharedContentAdmRouteRouteWithChildren =
  PrivatesharedContentAdmRouteRoute._addFileChildren(
    PrivatesharedContentAdmRouteRouteChildren,
  )

interface PrivateRouteRouteChildren {
  PrivateadmSharedRouteRoute: typeof PrivateadmSharedRouteRouteWithChildren
  PrivateclinicianRouteRoute: typeof PrivateclinicianRouteRouteWithChildren
  PrivatepatientRouteRoute: typeof PrivatepatientRouteRouteWithChildren
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateProfileEditRoute: typeof PrivateProfileEditRoute
  PrivateProfileIndexRoute: typeof PrivateProfileIndexRoute
  PrivatesharedContentAdmRouteRoute: typeof PrivatesharedContentAdmRouteRouteWithChildren
  PrivatesharedAppointmentsAppointmentIdRoute: typeof PrivatesharedAppointmentsAppointmentIdRoute
  PrivatesharedContentContentIdRoute: typeof PrivatesharedContentContentIdRoute
  PrivatesharedAppointmentsIndexRoute: typeof PrivatesharedAppointmentsIndexRoute
  PrivatesharedContentIndexRoute: typeof PrivatesharedContentIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateadmSharedRouteRoute: PrivateadmSharedRouteRouteWithChildren,
  PrivateclinicianRouteRoute: PrivateclinicianRouteRouteWithChildren,
  PrivatepatientRouteRoute: PrivatepatientRouteRouteWithChildren,
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateProfileEditRoute: PrivateProfileEditRoute,
  PrivateProfileIndexRoute: PrivateProfileIndexRoute,
  PrivatesharedContentAdmRouteRoute:
    PrivatesharedContentAdmRouteRouteWithChildren,
  PrivatesharedAppointmentsAppointmentIdRoute:
    PrivatesharedAppointmentsAppointmentIdRoute,
  PrivatesharedContentContentIdRoute: PrivatesharedContentContentIdRoute,
  PrivatesharedAppointmentsIndexRoute: PrivatesharedAppointmentsIndexRoute,
  PrivatesharedContentIndexRoute: PrivatesharedContentIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicActivateOtpUpdateRoute: typeof PublicActivateOtpUpdateRoute
  PublicActivateOtpIndexRoute: typeof PublicActivateOtpIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicActivateOtpUpdateRoute: PublicActivateOtpUpdateRoute,
  PublicActivateOtpIndexRoute: PublicActivateOtpIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
