import { t } from "elysia";

export const AppointmentModel = t.Object({
  id: t.String(),
  clinician_id: t.String(),
  patient_id: t.String(),
  schedule_instance_id: t.Optional(t.String()),
  appointment_room_id: t.Optional(t.String()),
  status: t.String(),
  starts_at: t.String(),
  ends_at: t.String(),
  created_at: t.String(),
  updated_at: t.String(),
  medical_diagnosis: t.Optional(t.String()),
  source_referral: t.Optional(t.String()),
  chief_complaint: t.Optional(t.String()),
  referral_url: t.Optional(t.String()),
  booked_at: t.Optional(t.String()),
  confirmed_at: t.Optional(t.String()),
  cancelled_at: t.Optional(t.String()),
  completed_at: t.Optional(t.String()),
  rescheduled_at: t.Optional(t.String()),
  cancelled_by: t.Optional(t.String()),
  patient_cancel_reason: t.Optional(t.String()),
  clinician_cancel_reason: t.Optional(t.String()),
  patient_reschedule_reason: t.Optional(t.String()),
  clinician_reschedule_reason: t.Optional(t.String()),
});

export const RescheduleRequestModel = t.Object({
  id: t.String(),
  appointment_id: t.String(),
  clinician_id: t.String(),
  patient_id: t.String(),
  original_schedule_instance_id: t.Optional(t.String()),
  requested_schedule_instance_id: t.Optional(t.String()),
  patient_reason: t.Optional(t.String()),
  clinician_reason: t.Optional(t.String()),
  status: t.String(),
  created_at: t.String(),
  updated_at: t.String(),
});
