/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PrivatePasswordRouteImport } from './routes/_private/password'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'
import { Route as PublicAuthRouteRouteImport } from './routes/_public/_auth/route'
import { Route as PrivatesudoRouteRouteImport } from './routes/_private/(sudo)/route'
import { Route as PrivatesharedRouteRouteImport } from './routes/_private/(shared)/route'
import { Route as PrivatepatientRouteRouteImport } from './routes/_private/(patient)/route'
import { Route as PrivateclinicianRouteRouteImport } from './routes/_private/(clinician)/route'
import { Route as PrivateadminRouteRouteImport } from './routes/_private/(admin)/route'
import { Route as PrivateadmSharedRouteRouteImport } from './routes/_private/(adm-shared)/route'
import { Route as PrivateProfileIndexRouteImport } from './routes/_private/profile.index'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/_auth/register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/_auth/login'
import { Route as PrivateProfileEditRouteImport } from './routes/_private/profile.edit'
import { Route as PrivatesudoLogsRouteImport } from './routes/_private/(sudo)/logs'
import { Route as PrivatesharedSchedulesIndexRouteImport } from './routes/_private/(shared)/schedules/index'
import { Route as PrivatesharedContentIndexRouteImport } from './routes/_private/(shared)/content/index'
import { Route as PrivatepatientRecordsIndexRouteImport } from './routes/_private/(patient)/records/index'
import { Route as PrivatepatientAppointmentsIndexRouteImport } from './routes/_private/(patient)/appointments/index'
import { Route as PrivateclinicianPatientsIndexRouteImport } from './routes/_private/(clinician)/patients/index'
import { Route as PrivateadmSharedUsersIndexRouteImport } from './routes/_private/(adm-shared)/users/index'
import { Route as PrivatesharedSchedulesCreateRouteImport } from './routes/_private/(shared)/schedules/create'
import { Route as PrivatesharedSchedulesScheduleIdRouteImport } from './routes/_private/(shared)/schedules/$scheduleId'
import { Route as PrivatesharedContentContentIdRouteImport } from './routes/_private/(shared)/content/$contentId'
import { Route as PrivatepatientAppointmentsAppointmentIdRouteImport } from './routes/_private/(patient)/appointments/$appointmentId'
import { Route as PrivateclinicianPatientsPatientIdRouteImport } from './routes/_private/(clinician)/patients/$patientId'
import { Route as PrivateadmSharedUsersUserIdRouteImport } from './routes/_private/(adm-shared)/users/$userId'
import { Route as PrivatesharedContentadminContentRouteRouteImport } from './routes/_private/(shared)/content/(admin-content)/route'
import { Route as PrivatesharedContentadminContentCreateRouteImport } from './routes/_private/(shared)/content/(admin-content)/create'
import { Route as PrivateadmSharedUsersUserIdEditRouteImport } from './routes/_private/(adm-shared)/users/$userId.edit'
import { Route as PrivatesharedContentadminContentContentIdEditRouteImport } from './routes/_private/(shared)/content/(admin-content)/$contentId.edit'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivatePasswordRoute = PrivatePasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicAuthRouteRoute = PublicAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivatesudoRouteRoute = PrivatesudoRouteRouteImport.update({
  id: '/(sudo)',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivatesharedRouteRoute = PrivatesharedRouteRouteImport.update({
  id: '/(shared)',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivatepatientRouteRoute = PrivatepatientRouteRouteImport.update({
  id: '/(patient)',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateclinicianRouteRoute = PrivateclinicianRouteRouteImport.update({
  id: '/(clinician)',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateadminRouteRoute = PrivateadminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateadmSharedRouteRoute = PrivateadmSharedRouteRouteImport.update({
  id: '/(adm-shared)',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateProfileIndexRoute = PrivateProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PrivateProfileEditRoute = PrivateProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivatesudoLogsRoute = PrivatesudoLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => PrivatesudoRouteRoute,
} as any)
const PrivatesharedSchedulesIndexRoute =
  PrivatesharedSchedulesIndexRouteImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => PrivatesharedRouteRoute,
  } as any)
const PrivatesharedContentIndexRoute =
  PrivatesharedContentIndexRouteImport.update({
    id: '/content/',
    path: '/content/',
    getParentRoute: () => PrivatesharedRouteRoute,
  } as any)
const PrivatepatientRecordsIndexRoute =
  PrivatepatientRecordsIndexRouteImport.update({
    id: '/records/',
    path: '/records/',
    getParentRoute: () => PrivatepatientRouteRoute,
  } as any)
const PrivatepatientAppointmentsIndexRoute =
  PrivatepatientAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => PrivatepatientRouteRoute,
  } as any)
const PrivateclinicianPatientsIndexRoute =
  PrivateclinicianPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => PrivateclinicianRouteRoute,
  } as any)
const PrivateadmSharedUsersIndexRoute =
  PrivateadmSharedUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => PrivateadmSharedRouteRoute,
  } as any)
const PrivatesharedSchedulesCreateRoute =
  PrivatesharedSchedulesCreateRouteImport.update({
    id: '/schedules/create',
    path: '/schedules/create',
    getParentRoute: () => PrivatesharedRouteRoute,
  } as any)
const PrivatesharedSchedulesScheduleIdRoute =
  PrivatesharedSchedulesScheduleIdRouteImport.update({
    id: '/schedules/$scheduleId',
    path: '/schedules/$scheduleId',
    getParentRoute: () => PrivatesharedRouteRoute,
  } as any)
const PrivatesharedContentContentIdRoute =
  PrivatesharedContentContentIdRouteImport.update({
    id: '/content/$contentId',
    path: '/content/$contentId',
    getParentRoute: () => PrivatesharedRouteRoute,
  } as any)
const PrivatepatientAppointmentsAppointmentIdRoute =
  PrivatepatientAppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => PrivatepatientRouteRoute,
  } as any)
const PrivateclinicianPatientsPatientIdRoute =
  PrivateclinicianPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => PrivateclinicianRouteRoute,
  } as any)
const PrivateadmSharedUsersUserIdRoute =
  PrivateadmSharedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => PrivateadmSharedRouteRoute,
  } as any)
const PrivatesharedContentadminContentRouteRoute =
  PrivatesharedContentadminContentRouteRouteImport.update({
    id: '/content/(admin-content)',
    path: '/content',
    getParentRoute: () => PrivatesharedRouteRoute,
  } as any)
const PrivatesharedContentadminContentCreateRoute =
  PrivatesharedContentadminContentCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => PrivatesharedContentadminContentRouteRoute,
  } as any)
const PrivateadmSharedUsersUserIdEditRoute =
  PrivateadmSharedUsersUserIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => PrivateadmSharedUsersUserIdRoute,
  } as any)
const PrivatesharedContentadminContentContentIdEditRoute =
  PrivatesharedContentadminContentContentIdEditRouteImport.update({
    id: '/$contentId/edit',
    path: '/$contentId/edit',
    getParentRoute: () => PrivatesharedContentadminContentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/password': typeof PrivatePasswordRoute
  '/logs': typeof PrivatesudoLogsRoute
  '/profile/edit': typeof PrivateProfileEditRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/profile/': typeof PrivateProfileIndexRoute
  '/content': typeof PrivatesharedContentadminContentRouteRouteWithChildren
  '/users/$userId': typeof PrivateadmSharedUsersUserIdRouteWithChildren
  '/patients/$patientId': typeof PrivateclinicianPatientsPatientIdRoute
  '/appointments/$appointmentId': typeof PrivatepatientAppointmentsAppointmentIdRoute
  '/content/$contentId': typeof PrivatesharedContentContentIdRoute
  '/schedules/$scheduleId': typeof PrivatesharedSchedulesScheduleIdRoute
  '/schedules/create': typeof PrivatesharedSchedulesCreateRoute
  '/users/': typeof PrivateadmSharedUsersIndexRoute
  '/patients/': typeof PrivateclinicianPatientsIndexRoute
  '/appointments/': typeof PrivatepatientAppointmentsIndexRoute
  '/records/': typeof PrivatepatientRecordsIndexRoute
  '/content/': typeof PrivatesharedContentIndexRoute
  '/schedules/': typeof PrivatesharedSchedulesIndexRoute
  '/users/$userId/edit': typeof PrivateadmSharedUsersUserIdEditRoute
  '/content/create': typeof PrivatesharedContentadminContentCreateRoute
  '/content/$contentId/edit': typeof PrivatesharedContentadminContentContentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/password': typeof PrivatePasswordRoute
  '/logs': typeof PrivatesudoLogsRoute
  '/profile/edit': typeof PrivateProfileEditRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/profile': typeof PrivateProfileIndexRoute
  '/content': typeof PrivatesharedContentIndexRoute
  '/users/$userId': typeof PrivateadmSharedUsersUserIdRouteWithChildren
  '/patients/$patientId': typeof PrivateclinicianPatientsPatientIdRoute
  '/appointments/$appointmentId': typeof PrivatepatientAppointmentsAppointmentIdRoute
  '/content/$contentId': typeof PrivatesharedContentContentIdRoute
  '/schedules/$scheduleId': typeof PrivatesharedSchedulesScheduleIdRoute
  '/schedules/create': typeof PrivatesharedSchedulesCreateRoute
  '/users': typeof PrivateadmSharedUsersIndexRoute
  '/patients': typeof PrivateclinicianPatientsIndexRoute
  '/appointments': typeof PrivatepatientAppointmentsIndexRoute
  '/records': typeof PrivatepatientRecordsIndexRoute
  '/schedules': typeof PrivatesharedSchedulesIndexRoute
  '/users/$userId/edit': typeof PrivateadmSharedUsersUserIdEditRoute
  '/content/create': typeof PrivatesharedContentadminContentCreateRoute
  '/content/$contentId/edit': typeof PrivatesharedContentadminContentContentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_private/(adm-shared)': typeof PrivateadmSharedRouteRouteWithChildren
  '/_private/(admin)': typeof PrivateadminRouteRoute
  '/_private/(clinician)': typeof PrivateclinicianRouteRouteWithChildren
  '/_private/(patient)': typeof PrivatepatientRouteRouteWithChildren
  '/_private/(shared)': typeof PrivatesharedRouteRouteWithChildren
  '/_private/(sudo)': typeof PrivatesudoRouteRouteWithChildren
  '/_public/_auth': typeof PublicAuthRouteRouteWithChildren
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/password': typeof PrivatePasswordRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/(sudo)/logs': typeof PrivatesudoLogsRoute
  '/_private/profile/edit': typeof PrivateProfileEditRoute
  '/_public/_auth/login': typeof PublicAuthLoginRoute
  '/_public/_auth/register': typeof PublicAuthRegisterRoute
  '/_private/profile/': typeof PrivateProfileIndexRoute
  '/_private/(shared)/content/(admin-content)': typeof PrivatesharedContentadminContentRouteRouteWithChildren
  '/_private/(adm-shared)/users/$userId': typeof PrivateadmSharedUsersUserIdRouteWithChildren
  '/_private/(clinician)/patients/$patientId': typeof PrivateclinicianPatientsPatientIdRoute
  '/_private/(patient)/appointments/$appointmentId': typeof PrivatepatientAppointmentsAppointmentIdRoute
  '/_private/(shared)/content/$contentId': typeof PrivatesharedContentContentIdRoute
  '/_private/(shared)/schedules/$scheduleId': typeof PrivatesharedSchedulesScheduleIdRoute
  '/_private/(shared)/schedules/create': typeof PrivatesharedSchedulesCreateRoute
  '/_private/(adm-shared)/users/': typeof PrivateadmSharedUsersIndexRoute
  '/_private/(clinician)/patients/': typeof PrivateclinicianPatientsIndexRoute
  '/_private/(patient)/appointments/': typeof PrivatepatientAppointmentsIndexRoute
  '/_private/(patient)/records/': typeof PrivatepatientRecordsIndexRoute
  '/_private/(shared)/content/': typeof PrivatesharedContentIndexRoute
  '/_private/(shared)/schedules/': typeof PrivatesharedSchedulesIndexRoute
  '/_private/(adm-shared)/users/$userId/edit': typeof PrivateadmSharedUsersUserIdEditRoute
  '/_private/(shared)/content/(admin-content)/create': typeof PrivatesharedContentadminContentCreateRoute
  '/_private/(shared)/content/(admin-content)/$contentId/edit': typeof PrivatesharedContentadminContentContentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unauthorized'
    | '/dashboard'
    | '/password'
    | '/logs'
    | '/profile/edit'
    | '/login'
    | '/register'
    | '/profile/'
    | '/content'
    | '/users/$userId'
    | '/patients/$patientId'
    | '/appointments/$appointmentId'
    | '/content/$contentId'
    | '/schedules/$scheduleId'
    | '/schedules/create'
    | '/users/'
    | '/patients/'
    | '/appointments/'
    | '/records/'
    | '/content/'
    | '/schedules/'
    | '/users/$userId/edit'
    | '/content/create'
    | '/content/$contentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/dashboard'
    | '/password'
    | '/logs'
    | '/profile/edit'
    | '/login'
    | '/register'
    | '/profile'
    | '/content'
    | '/users/$userId'
    | '/patients/$patientId'
    | '/appointments/$appointmentId'
    | '/content/$contentId'
    | '/schedules/$scheduleId'
    | '/schedules/create'
    | '/users'
    | '/patients'
    | '/appointments'
    | '/records'
    | '/schedules'
    | '/users/$userId/edit'
    | '/content/create'
    | '/content/$contentId/edit'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/unauthorized'
    | '/_private/(adm-shared)'
    | '/_private/(admin)'
    | '/_private/(clinician)'
    | '/_private/(patient)'
    | '/_private/(shared)'
    | '/_private/(sudo)'
    | '/_public/_auth'
    | '/_private/dashboard'
    | '/_private/password'
    | '/_public/'
    | '/_private/(sudo)/logs'
    | '/_private/profile/edit'
    | '/_public/_auth/login'
    | '/_public/_auth/register'
    | '/_private/profile/'
    | '/_private/(shared)/content/(admin-content)'
    | '/_private/(adm-shared)/users/$userId'
    | '/_private/(clinician)/patients/$patientId'
    | '/_private/(patient)/appointments/$appointmentId'
    | '/_private/(shared)/content/$contentId'
    | '/_private/(shared)/schedules/$scheduleId'
    | '/_private/(shared)/schedules/create'
    | '/_private/(adm-shared)/users/'
    | '/_private/(clinician)/patients/'
    | '/_private/(patient)/appointments/'
    | '/_private/(patient)/records/'
    | '/_private/(shared)/content/'
    | '/_private/(shared)/schedules/'
    | '/_private/(adm-shared)/users/$userId/edit'
    | '/_private/(shared)/content/(admin-content)/create'
    | '/_private/(shared)/content/(admin-content)/$contentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/password': {
      id: '/_private/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PrivatePasswordRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicAuthRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/(sudo)': {
      id: '/_private/(sudo)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivatesudoRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(shared)': {
      id: '/_private/(shared)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivatesharedRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(patient)': {
      id: '/_private/(patient)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivatepatientRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(clinician)': {
      id: '/_private/(clinician)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateclinicianRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(admin)': {
      id: '/_private/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateadminRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(adm-shared)': {
      id: '/_private/(adm-shared)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateadmSharedRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/profile/': {
      id: '/_private/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof PrivateProfileIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/_auth/register': {
      id: '/_public/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/login': {
      id: '/_public/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_private/profile/edit': {
      id: '/_private/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof PrivateProfileEditRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/(sudo)/logs': {
      id: '/_private/(sudo)/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof PrivatesudoLogsRouteImport
      parentRoute: typeof PrivatesudoRouteRoute
    }
    '/_private/(shared)/schedules/': {
      id: '/_private/(shared)/schedules/'
      path: '/schedules'
      fullPath: '/schedules/'
      preLoaderRoute: typeof PrivatesharedSchedulesIndexRouteImport
      parentRoute: typeof PrivatesharedRouteRoute
    }
    '/_private/(shared)/content/': {
      id: '/_private/(shared)/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof PrivatesharedContentIndexRouteImport
      parentRoute: typeof PrivatesharedRouteRoute
    }
    '/_private/(patient)/records/': {
      id: '/_private/(patient)/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof PrivatepatientRecordsIndexRouteImport
      parentRoute: typeof PrivatepatientRouteRoute
    }
    '/_private/(patient)/appointments/': {
      id: '/_private/(patient)/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof PrivatepatientAppointmentsIndexRouteImport
      parentRoute: typeof PrivatepatientRouteRoute
    }
    '/_private/(clinician)/patients/': {
      id: '/_private/(clinician)/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PrivateclinicianPatientsIndexRouteImport
      parentRoute: typeof PrivateclinicianRouteRoute
    }
    '/_private/(adm-shared)/users/': {
      id: '/_private/(adm-shared)/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof PrivateadmSharedUsersIndexRouteImport
      parentRoute: typeof PrivateadmSharedRouteRoute
    }
    '/_private/(shared)/schedules/create': {
      id: '/_private/(shared)/schedules/create'
      path: '/schedules/create'
      fullPath: '/schedules/create'
      preLoaderRoute: typeof PrivatesharedSchedulesCreateRouteImport
      parentRoute: typeof PrivatesharedRouteRoute
    }
    '/_private/(shared)/schedules/$scheduleId': {
      id: '/_private/(shared)/schedules/$scheduleId'
      path: '/schedules/$scheduleId'
      fullPath: '/schedules/$scheduleId'
      preLoaderRoute: typeof PrivatesharedSchedulesScheduleIdRouteImport
      parentRoute: typeof PrivatesharedRouteRoute
    }
    '/_private/(shared)/content/$contentId': {
      id: '/_private/(shared)/content/$contentId'
      path: '/content/$contentId'
      fullPath: '/content/$contentId'
      preLoaderRoute: typeof PrivatesharedContentContentIdRouteImport
      parentRoute: typeof PrivatesharedRouteRoute
    }
    '/_private/(patient)/appointments/$appointmentId': {
      id: '/_private/(patient)/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof PrivatepatientAppointmentsAppointmentIdRouteImport
      parentRoute: typeof PrivatepatientRouteRoute
    }
    '/_private/(clinician)/patients/$patientId': {
      id: '/_private/(clinician)/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PrivateclinicianPatientsPatientIdRouteImport
      parentRoute: typeof PrivateclinicianRouteRoute
    }
    '/_private/(adm-shared)/users/$userId': {
      id: '/_private/(adm-shared)/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof PrivateadmSharedUsersUserIdRouteImport
      parentRoute: typeof PrivateadmSharedRouteRoute
    }
    '/_private/(shared)/content/(admin-content)': {
      id: '/_private/(shared)/content/(admin-content)'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof PrivatesharedContentadminContentRouteRouteImport
      parentRoute: typeof PrivatesharedRouteRoute
    }
    '/_private/(shared)/content/(admin-content)/create': {
      id: '/_private/(shared)/content/(admin-content)/create'
      path: '/create'
      fullPath: '/content/create'
      preLoaderRoute: typeof PrivatesharedContentadminContentCreateRouteImport
      parentRoute: typeof PrivatesharedContentadminContentRouteRoute
    }
    '/_private/(adm-shared)/users/$userId/edit': {
      id: '/_private/(adm-shared)/users/$userId/edit'
      path: '/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof PrivateadmSharedUsersUserIdEditRouteImport
      parentRoute: typeof PrivateadmSharedUsersUserIdRoute
    }
    '/_private/(shared)/content/(admin-content)/$contentId/edit': {
      id: '/_private/(shared)/content/(admin-content)/$contentId/edit'
      path: '/$contentId/edit'
      fullPath: '/content/$contentId/edit'
      preLoaderRoute: typeof PrivatesharedContentadminContentContentIdEditRouteImport
      parentRoute: typeof PrivatesharedContentadminContentRouteRoute
    }
  }
}

interface PrivateadmSharedUsersUserIdRouteChildren {
  PrivateadmSharedUsersUserIdEditRoute: typeof PrivateadmSharedUsersUserIdEditRoute
}

const PrivateadmSharedUsersUserIdRouteChildren: PrivateadmSharedUsersUserIdRouteChildren =
  {
    PrivateadmSharedUsersUserIdEditRoute: PrivateadmSharedUsersUserIdEditRoute,
  }

const PrivateadmSharedUsersUserIdRouteWithChildren =
  PrivateadmSharedUsersUserIdRoute._addFileChildren(
    PrivateadmSharedUsersUserIdRouteChildren,
  )

interface PrivateadmSharedRouteRouteChildren {
  PrivateadmSharedUsersUserIdRoute: typeof PrivateadmSharedUsersUserIdRouteWithChildren
  PrivateadmSharedUsersIndexRoute: typeof PrivateadmSharedUsersIndexRoute
}

const PrivateadmSharedRouteRouteChildren: PrivateadmSharedRouteRouteChildren = {
  PrivateadmSharedUsersUserIdRoute:
    PrivateadmSharedUsersUserIdRouteWithChildren,
  PrivateadmSharedUsersIndexRoute: PrivateadmSharedUsersIndexRoute,
}

const PrivateadmSharedRouteRouteWithChildren =
  PrivateadmSharedRouteRoute._addFileChildren(
    PrivateadmSharedRouteRouteChildren,
  )

interface PrivateclinicianRouteRouteChildren {
  PrivateclinicianPatientsPatientIdRoute: typeof PrivateclinicianPatientsPatientIdRoute
  PrivateclinicianPatientsIndexRoute: typeof PrivateclinicianPatientsIndexRoute
}

const PrivateclinicianRouteRouteChildren: PrivateclinicianRouteRouteChildren = {
  PrivateclinicianPatientsPatientIdRoute:
    PrivateclinicianPatientsPatientIdRoute,
  PrivateclinicianPatientsIndexRoute: PrivateclinicianPatientsIndexRoute,
}

const PrivateclinicianRouteRouteWithChildren =
  PrivateclinicianRouteRoute._addFileChildren(
    PrivateclinicianRouteRouteChildren,
  )

interface PrivatepatientRouteRouteChildren {
  PrivatepatientAppointmentsAppointmentIdRoute: typeof PrivatepatientAppointmentsAppointmentIdRoute
  PrivatepatientAppointmentsIndexRoute: typeof PrivatepatientAppointmentsIndexRoute
  PrivatepatientRecordsIndexRoute: typeof PrivatepatientRecordsIndexRoute
}

const PrivatepatientRouteRouteChildren: PrivatepatientRouteRouteChildren = {
  PrivatepatientAppointmentsAppointmentIdRoute:
    PrivatepatientAppointmentsAppointmentIdRoute,
  PrivatepatientAppointmentsIndexRoute: PrivatepatientAppointmentsIndexRoute,
  PrivatepatientRecordsIndexRoute: PrivatepatientRecordsIndexRoute,
}

const PrivatepatientRouteRouteWithChildren =
  PrivatepatientRouteRoute._addFileChildren(PrivatepatientRouteRouteChildren)

interface PrivatesharedContentadminContentRouteRouteChildren {
  PrivatesharedContentadminContentCreateRoute: typeof PrivatesharedContentadminContentCreateRoute
  PrivatesharedContentadminContentContentIdEditRoute: typeof PrivatesharedContentadminContentContentIdEditRoute
}

const PrivatesharedContentadminContentRouteRouteChildren: PrivatesharedContentadminContentRouteRouteChildren =
  {
    PrivatesharedContentadminContentCreateRoute:
      PrivatesharedContentadminContentCreateRoute,
    PrivatesharedContentadminContentContentIdEditRoute:
      PrivatesharedContentadminContentContentIdEditRoute,
  }

const PrivatesharedContentadminContentRouteRouteWithChildren =
  PrivatesharedContentadminContentRouteRoute._addFileChildren(
    PrivatesharedContentadminContentRouteRouteChildren,
  )

interface PrivatesharedRouteRouteChildren {
  PrivatesharedContentadminContentRouteRoute: typeof PrivatesharedContentadminContentRouteRouteWithChildren
  PrivatesharedContentContentIdRoute: typeof PrivatesharedContentContentIdRoute
  PrivatesharedSchedulesScheduleIdRoute: typeof PrivatesharedSchedulesScheduleIdRoute
  PrivatesharedSchedulesCreateRoute: typeof PrivatesharedSchedulesCreateRoute
  PrivatesharedContentIndexRoute: typeof PrivatesharedContentIndexRoute
  PrivatesharedSchedulesIndexRoute: typeof PrivatesharedSchedulesIndexRoute
}

const PrivatesharedRouteRouteChildren: PrivatesharedRouteRouteChildren = {
  PrivatesharedContentadminContentRouteRoute:
    PrivatesharedContentadminContentRouteRouteWithChildren,
  PrivatesharedContentContentIdRoute: PrivatesharedContentContentIdRoute,
  PrivatesharedSchedulesScheduleIdRoute: PrivatesharedSchedulesScheduleIdRoute,
  PrivatesharedSchedulesCreateRoute: PrivatesharedSchedulesCreateRoute,
  PrivatesharedContentIndexRoute: PrivatesharedContentIndexRoute,
  PrivatesharedSchedulesIndexRoute: PrivatesharedSchedulesIndexRoute,
}

const PrivatesharedRouteRouteWithChildren =
  PrivatesharedRouteRoute._addFileChildren(PrivatesharedRouteRouteChildren)

interface PrivatesudoRouteRouteChildren {
  PrivatesudoLogsRoute: typeof PrivatesudoLogsRoute
}

const PrivatesudoRouteRouteChildren: PrivatesudoRouteRouteChildren = {
  PrivatesudoLogsRoute: PrivatesudoLogsRoute,
}

const PrivatesudoRouteRouteWithChildren =
  PrivatesudoRouteRoute._addFileChildren(PrivatesudoRouteRouteChildren)

interface PrivateRouteRouteChildren {
  PrivateadmSharedRouteRoute: typeof PrivateadmSharedRouteRouteWithChildren
  PrivateadminRouteRoute: typeof PrivateadminRouteRoute
  PrivateclinicianRouteRoute: typeof PrivateclinicianRouteRouteWithChildren
  PrivatepatientRouteRoute: typeof PrivatepatientRouteRouteWithChildren
  PrivatesharedRouteRoute: typeof PrivatesharedRouteRouteWithChildren
  PrivatesudoRouteRoute: typeof PrivatesudoRouteRouteWithChildren
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivatePasswordRoute: typeof PrivatePasswordRoute
  PrivateProfileEditRoute: typeof PrivateProfileEditRoute
  PrivateProfileIndexRoute: typeof PrivateProfileIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateadmSharedRouteRoute: PrivateadmSharedRouteRouteWithChildren,
  PrivateadminRouteRoute: PrivateadminRouteRoute,
  PrivateclinicianRouteRoute: PrivateclinicianRouteRouteWithChildren,
  PrivatepatientRouteRoute: PrivatepatientRouteRouteWithChildren,
  PrivatesharedRouteRoute: PrivatesharedRouteRouteWithChildren,
  PrivatesudoRouteRoute: PrivatesudoRouteRouteWithChildren,
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivatePasswordRoute: PrivatePasswordRoute,
  PrivateProfileEditRoute: PrivateProfileEditRoute,
  PrivateProfileIndexRoute: PrivateProfileIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicAuthRouteRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
}

const PublicAuthRouteRouteChildren: PublicAuthRouteRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
}

const PublicAuthRouteRouteWithChildren = PublicAuthRouteRoute._addFileChildren(
  PublicAuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthRouteRoute: typeof PublicAuthRouteRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthRouteRoute: PublicAuthRouteRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
