/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as privateAuthRouteRouteImport } from './routes/(private)/_auth/route'
import { Route as ApiUsersIdRouteImport } from './routes/api/users.$id'
import { Route as publicmarketingAboutRouteImport } from './routes/(public)/(marketing)/about'
import { Route as publicauthAuthPagesRouteRouteImport } from './routes/(public)/(auth)/_auth-pages/route'
import { Route as privateAuthRoleLayoutRouteRouteImport } from './routes/(private)/_auth/_role-layout/route'
import { Route as publicauthAuthPagesRegisterRouteImport } from './routes/(public)/(auth)/_auth-pages/register'
import { Route as publicauthAuthPagesLoginRouteImport } from './routes/(public)/(auth)/_auth-pages/login'
import { Route as privateAuthRoleLayoutDashboardRouteImport } from './routes/(private)/_auth/_role-layout/dashboard'
import { Route as privateAuthRoleLayoutsudoRouteRouteImport } from './routes/(private)/_auth/_role-layout/(sudo)/route'
import { Route as privateAuthRoleLayoutsudoLogsRouteImport } from './routes/(private)/_auth/_role-layout/(sudo)/logs'
import { Route as privateAuthRoleLayoutadmSharedUsersRouteImport } from './routes/(private)/_auth/_role-layout/(adm-shared)/users'
import { Route as privateAuthRoleLayoutadmSharedSettingsRouteImport } from './routes/(private)/_auth/_role-layout/(adm-shared)/settings'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const privateAuthRouteRoute = privateAuthRouteRouteImport.update({
  id: '/(private)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const publicmarketingAboutRoute = publicmarketingAboutRouteImport.update({
  id: '/(marketing)/about',
  path: '/about',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicauthAuthPagesRouteRoute =
  publicauthAuthPagesRouteRouteImport.update({
    id: '/(auth)/_auth-pages',
    getParentRoute: () => publicRouteRoute,
  } as any)
const privateAuthRoleLayoutRouteRoute =
  privateAuthRoleLayoutRouteRouteImport.update({
    id: '/_role-layout',
    getParentRoute: () => privateAuthRouteRoute,
  } as any)
const publicauthAuthPagesRegisterRoute =
  publicauthAuthPagesRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => publicauthAuthPagesRouteRoute,
  } as any)
const publicauthAuthPagesLoginRoute =
  publicauthAuthPagesLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => publicauthAuthPagesRouteRoute,
  } as any)
const privateAuthRoleLayoutDashboardRoute =
  privateAuthRoleLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => privateAuthRoleLayoutRouteRoute,
  } as any)
const privateAuthRoleLayoutsudoRouteRoute =
  privateAuthRoleLayoutsudoRouteRouteImport.update({
    id: '/(sudo)',
    getParentRoute: () => privateAuthRoleLayoutRouteRoute,
  } as any)
const privateAuthRoleLayoutsudoLogsRoute =
  privateAuthRoleLayoutsudoLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => privateAuthRoleLayoutsudoRouteRoute,
  } as any)
const privateAuthRoleLayoutadmSharedUsersRoute =
  privateAuthRoleLayoutadmSharedUsersRouteImport.update({
    id: '/(adm-shared)/users',
    path: '/users',
    getParentRoute: () => privateAuthRoleLayoutRouteRoute,
  } as any)
const privateAuthRoleLayoutadmSharedSettingsRoute =
  privateAuthRoleLayoutadmSharedSettingsRouteImport.update({
    id: '/(adm-shared)/settings',
    path: '/settings',
    getParentRoute: () => privateAuthRoleLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/redirect': typeof RedirectRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/about': typeof publicmarketingAboutRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/dashboard': typeof privateAuthRoleLayoutDashboardRoute
  '/login': typeof publicauthAuthPagesLoginRoute
  '/register': typeof publicauthAuthPagesRegisterRoute
  '/settings': typeof privateAuthRoleLayoutadmSharedSettingsRoute
  '/users': typeof privateAuthRoleLayoutadmSharedUsersRoute
  '/logs': typeof privateAuthRoleLayoutsudoLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/redirect': typeof RedirectRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/about': typeof publicmarketingAboutRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/dashboard': typeof privateAuthRoleLayoutDashboardRoute
  '/login': typeof publicauthAuthPagesLoginRoute
  '/register': typeof publicauthAuthPagesRegisterRoute
  '/settings': typeof privateAuthRoleLayoutadmSharedSettingsRoute
  '/users': typeof privateAuthRoleLayoutadmSharedUsersRoute
  '/logs': typeof privateAuthRoleLayoutsudoLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(public)': typeof publicRouteRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/redirect': typeof RedirectRoute
  '/(private)/_auth': typeof privateAuthRouteRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/(private)/_auth/_role-layout': typeof privateAuthRoleLayoutRouteRouteWithChildren
  '/(public)/(auth)/_auth-pages': typeof publicauthAuthPagesRouteRouteWithChildren
  '/(public)/(marketing)/about': typeof publicmarketingAboutRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/(private)/_auth/_role-layout/(sudo)': typeof privateAuthRoleLayoutsudoRouteRouteWithChildren
  '/(private)/_auth/_role-layout/dashboard': typeof privateAuthRoleLayoutDashboardRoute
  '/(public)/(auth)/_auth-pages/login': typeof publicauthAuthPagesLoginRoute
  '/(public)/(auth)/_auth-pages/register': typeof publicauthAuthPagesRegisterRoute
  '/(private)/_auth/_role-layout/(adm-shared)/settings': typeof privateAuthRoleLayoutadmSharedSettingsRoute
  '/(private)/_auth/_role-layout/(adm-shared)/users': typeof privateAuthRoleLayoutadmSharedUsersRoute
  '/(private)/_auth/_role-layout/(sudo)/logs': typeof privateAuthRoleLayoutsudoLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deferred'
    | '/redirect'
    | '/api/users'
    | '/about'
    | '/api/users/$id'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/settings'
    | '/users'
    | '/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deferred'
    | '/redirect'
    | '/api/users'
    | '/about'
    | '/api/users/$id'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/settings'
    | '/users'
    | '/logs'
  id:
    | '__root__'
    | '/'
    | '/(public)'
    | '/deferred'
    | '/redirect'
    | '/(private)/_auth'
    | '/api/users'
    | '/(private)/_auth/_role-layout'
    | '/(public)/(auth)/_auth-pages'
    | '/(public)/(marketing)/about'
    | '/api/users/$id'
    | '/(private)/_auth/_role-layout/(sudo)'
    | '/(private)/_auth/_role-layout/dashboard'
    | '/(public)/(auth)/_auth-pages/login'
    | '/(public)/(auth)/_auth-pages/register'
    | '/(private)/_auth/_role-layout/(adm-shared)/settings'
    | '/(private)/_auth/_role-layout/(adm-shared)/users'
    | '/(private)/_auth/_role-layout/(sudo)/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  publicRouteRoute: typeof publicRouteRouteWithChildren
  DeferredRoute: typeof DeferredRoute
  RedirectRoute: typeof RedirectRoute
  privateAuthRouteRoute: typeof privateAuthRouteRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_auth': {
      id: '/(private)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/(public)/(marketing)/about': {
      id: '/(public)/(marketing)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicmarketingAboutRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(auth)/_auth-pages': {
      id: '/(public)/(auth)/_auth-pages'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicauthAuthPagesRouteRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(private)/_auth/_role-layout': {
      id: '/(private)/_auth/_role-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateAuthRoleLayoutRouteRouteImport
      parentRoute: typeof privateAuthRouteRoute
    }
    '/(public)/(auth)/_auth-pages/register': {
      id: '/(public)/(auth)/_auth-pages/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicauthAuthPagesRegisterRouteImport
      parentRoute: typeof publicauthAuthPagesRouteRoute
    }
    '/(public)/(auth)/_auth-pages/login': {
      id: '/(public)/(auth)/_auth-pages/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicauthAuthPagesLoginRouteImport
      parentRoute: typeof publicauthAuthPagesRouteRoute
    }
    '/(private)/_auth/_role-layout/dashboard': {
      id: '/(private)/_auth/_role-layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privateAuthRoleLayoutDashboardRouteImport
      parentRoute: typeof privateAuthRoleLayoutRouteRoute
    }
    '/(private)/_auth/_role-layout/(sudo)': {
      id: '/(private)/_auth/_role-layout/(sudo)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateAuthRoleLayoutsudoRouteRouteImport
      parentRoute: typeof privateAuthRoleLayoutRouteRoute
    }
    '/(private)/_auth/_role-layout/(sudo)/logs': {
      id: '/(private)/_auth/_role-layout/(sudo)/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof privateAuthRoleLayoutsudoLogsRouteImport
      parentRoute: typeof privateAuthRoleLayoutsudoRouteRoute
    }
    '/(private)/_auth/_role-layout/(adm-shared)/users': {
      id: '/(private)/_auth/_role-layout/(adm-shared)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof privateAuthRoleLayoutadmSharedUsersRouteImport
      parentRoute: typeof privateAuthRoleLayoutRouteRoute
    }
    '/(private)/_auth/_role-layout/(adm-shared)/settings': {
      id: '/(private)/_auth/_role-layout/(adm-shared)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof privateAuthRoleLayoutadmSharedSettingsRouteImport
      parentRoute: typeof privateAuthRoleLayoutRouteRoute
    }
  }
}

interface publicauthAuthPagesRouteRouteChildren {
  publicauthAuthPagesLoginRoute: typeof publicauthAuthPagesLoginRoute
  publicauthAuthPagesRegisterRoute: typeof publicauthAuthPagesRegisterRoute
}

const publicauthAuthPagesRouteRouteChildren: publicauthAuthPagesRouteRouteChildren =
  {
    publicauthAuthPagesLoginRoute: publicauthAuthPagesLoginRoute,
    publicauthAuthPagesRegisterRoute: publicauthAuthPagesRegisterRoute,
  }

const publicauthAuthPagesRouteRouteWithChildren =
  publicauthAuthPagesRouteRoute._addFileChildren(
    publicauthAuthPagesRouteRouteChildren,
  )

interface publicRouteRouteChildren {
  publicauthAuthPagesRouteRoute: typeof publicauthAuthPagesRouteRouteWithChildren
  publicmarketingAboutRoute: typeof publicmarketingAboutRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicauthAuthPagesRouteRoute: publicauthAuthPagesRouteRouteWithChildren,
  publicmarketingAboutRoute: publicmarketingAboutRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface privateAuthRoleLayoutsudoRouteRouteChildren {
  privateAuthRoleLayoutsudoLogsRoute: typeof privateAuthRoleLayoutsudoLogsRoute
}

const privateAuthRoleLayoutsudoRouteRouteChildren: privateAuthRoleLayoutsudoRouteRouteChildren =
  {
    privateAuthRoleLayoutsudoLogsRoute: privateAuthRoleLayoutsudoLogsRoute,
  }

const privateAuthRoleLayoutsudoRouteRouteWithChildren =
  privateAuthRoleLayoutsudoRouteRoute._addFileChildren(
    privateAuthRoleLayoutsudoRouteRouteChildren,
  )

interface privateAuthRoleLayoutRouteRouteChildren {
  privateAuthRoleLayoutsudoRouteRoute: typeof privateAuthRoleLayoutsudoRouteRouteWithChildren
  privateAuthRoleLayoutDashboardRoute: typeof privateAuthRoleLayoutDashboardRoute
  privateAuthRoleLayoutadmSharedSettingsRoute: typeof privateAuthRoleLayoutadmSharedSettingsRoute
  privateAuthRoleLayoutadmSharedUsersRoute: typeof privateAuthRoleLayoutadmSharedUsersRoute
}

const privateAuthRoleLayoutRouteRouteChildren: privateAuthRoleLayoutRouteRouteChildren =
  {
    privateAuthRoleLayoutsudoRouteRoute:
      privateAuthRoleLayoutsudoRouteRouteWithChildren,
    privateAuthRoleLayoutDashboardRoute: privateAuthRoleLayoutDashboardRoute,
    privateAuthRoleLayoutadmSharedSettingsRoute:
      privateAuthRoleLayoutadmSharedSettingsRoute,
    privateAuthRoleLayoutadmSharedUsersRoute:
      privateAuthRoleLayoutadmSharedUsersRoute,
  }

const privateAuthRoleLayoutRouteRouteWithChildren =
  privateAuthRoleLayoutRouteRoute._addFileChildren(
    privateAuthRoleLayoutRouteRouteChildren,
  )

interface privateAuthRouteRouteChildren {
  privateAuthRoleLayoutRouteRoute: typeof privateAuthRoleLayoutRouteRouteWithChildren
}

const privateAuthRouteRouteChildren: privateAuthRouteRouteChildren = {
  privateAuthRoleLayoutRouteRoute: privateAuthRoleLayoutRouteRouteWithChildren,
}

const privateAuthRouteRouteWithChildren =
  privateAuthRouteRoute._addFileChildren(privateAuthRouteRouteChildren)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  publicRouteRoute: publicRouteRouteWithChildren,
  DeferredRoute: DeferredRoute,
  RedirectRoute: RedirectRoute,
  privateAuthRouteRoute: privateAuthRouteRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
